### ISSUE TITLE
Question about cygfuse_report and /var/run/fuse.mount

### ISSUE THREAD

**Issue by joachimmetz** [mgeisert/cygfuse#5]
I have a binary that is able to fuse mount using cygfuse+winfsp.

However unmouting via `fusermount -u` is not working. It appears `/var/run/fuse.mounts` is not created

I was looking through the source and see that cygfuse_report is the function that writes `/var/run/fuse.mounts`. However it is unclear to me where/how this function should be invoked.

What I want to accomplish is that `/var/run/fuse.mounts` is updated so that the fuse file system can be unmounted via `fusermount -u` . I can re-implement cygfuse_report in the binary but is that the intended way?

**Comment by mgeisert** [comment]
(Apologies for delayed response; vacation interference.)
The cygfuse_report() function needs better documentation.

Any FUSE application ported from Linux or built specifically for Cygwin needs to have a call to cygfuse_report() somewhere in its source. Ideally the call should be placed after all program option processing has been done and (usually) before the first call to a FUSE library function. 

Take a look at sshfs.c as built in Cygwin's sshfs package for an example. In this case care had to be taken to place the cygfuse_report() call after fuse_daemonize(), so that the child process, i.e., the process actually doing FUSE operations, does the reporting.

**Comment by joachimmetz** [comment]
Thanks for additional context, no problem I did not expect an immediate answer. I'll take a closer look sshfs source.
